/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import CLASES.Conection;
import CLASES.DatosCompartidos;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author herna
 */
public class Egresos extends javax.swing.JFrame {

    /**
     * Creates new form Egresos
     */
    
     private String nombreAnterior;
       private String contraseñaAnterior;
       
       public Egresos(String name, String pass) {
         String nombreAnterior = DatosCompartidos.name;
        String contraseñaAnterior = DatosCompartidos.pass;
        
       

        // Resto del código del constructor de NuevaVentana
    }
    public Egresos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tablaretiros = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCantidadE = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtFechaEgreso = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtDescripE = new javax.swing.JTextField();
        BTNegresos = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 36)); // NOI18N
        jLabel1.setText("RETIROS");

        jButton1.setText("ATRAS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Tablaretiros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Tablaretiros);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Registrar Egreso");

        jLabel3.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cantidad");

        txtCantidadE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadEActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Fecha Retiro");

        txtFechaEgreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaEgresoActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Descripción");

        txtDescripE.setText(" ");

        BTNegresos.setText(" ENVIAR");
        BTNegresos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNegresosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCantidadE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFechaEgreso)
                            .addComponent(txtDescripE, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(BTNegresos)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addGap(42, 42, 42)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCantidadE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(txtFechaEgreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(txtDescripE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BTNegresos)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jButton2.setText("Mostrar Egresos");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(jButton2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)
                        .addGap(1, 1, 1)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Home oforma = new Home();
        oforma.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BTNegresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNegresosActionPerformed
        // TODO add your handling code here:
        
        insertaregreso();
          tablach();
    }//GEN-LAST:event_BTNegresosActionPerformed

    private void txtFechaEgresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaEgresoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaEgresoActionPerformed

    private void txtCantidadEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadEActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        tablach();
   
    }//GEN-LAST:event_jButton2ActionPerformed
 
    private void tablach(){
         
        // Obtener el nombre y la contraseña ingresados
  String nombreAnterior = DatosCompartidos.name;
        String contraseñaAnterior = DatosCompartidos.pass;

// Realizar la consulta para obtener los datos relacionados
String query = "SELECT * FROM Retiros WHERE IdUsuario IN (SELECT IdUsuario FROM CrearUsuario WHERE Nombres = ? AND Contraseña = ?)";
try {
    Connection connection = Conection.getConexion();
    PreparedStatement statement = connection.prepareStatement(query);
    statement.setString(1, nombreAnterior);
    statement.setString(2, contraseñaAnterior);
    ResultSet resultSet = statement.executeQuery();

    // Crear un modelo de tabla
    DefaultTableModel model = new DefaultTableModel();

    // Configurar las columnas y encabezados
    ResultSetMetaData metaData = resultSet.getMetaData();
    int columnCount = metaData.getColumnCount();
    for (int i = 1; i <= columnCount; i++) {
        model.addColumn(metaData.getColumnName(i));
    }

    // Recorrer los resultados y agregar las filas al modelo
    while (resultSet.next()) {
        Object[] row = new Object[columnCount];
        for (int i = 1; i <= columnCount; i++) {
            row[i - 1] = resultSet.getObject(i);
        }
        model.addRow(row);
    }

    // Asignar el modelo a la tabla
    Tablaretiros.setModel(model);

    // Cerrar los recursos
    resultSet.close();
    statement.close();
    connection.close();
} catch (SQLException e) {
    e.printStackTrace();
}

    
    
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Egresos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Egresos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Egresos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Egresos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Egresos().setVisible(true);
            }
        });
    }
    
    public void insertaregreso(){
        
     String nombreAnterior = DatosCompartidos.name;
    String contraseñaAnterior = DatosCompartidos.pass;

// Obtener los valores para los nuevos ingresos
    
    double cant = Double.parseDouble(txtCantidadE.getText());
    Date fecha = Date.valueOf(txtFechaEgreso.getText());
String descripcion = txtDescripE.getText();
    
    try {
    // Obtener la conexión desde la clase Connection
    Connection connection = Conection.getConexion();

    // Construir la consulta SQL para llamar al procedimiento almacenado
    String query = "{CALL InsertarRetiro(?, ?, ?, ?, ?)}";

    // Crear el CallableStatement y establecer los parámetros
    CallableStatement statement = connection.prepareCall(query);
    statement.setString(1, nombreAnterior);
    statement.setString(2, contraseñaAnterior);
    statement.setDouble(3, cant);
    statement.setDate(4, fecha);
    statement.setString(5, descripcion);

    // Ejecutar la consulta
    statement.execute();
    JOptionPane.showMessageDialog(null, "Egreso registrado correctamente.");
    // Cerrar los recursos
    statement.close();
    connection.close();
} catch (SQLException e) {
    e.printStackTrace();
}



    
    
    
    }
    
    
  public void tabla(){
      
      String nombreAnterior = DatosCompartidos.name;
        String contraseñaAnterior = DatosCompartidos.pass;
      try {
    // Obtener la conexión desde la clase Connection
    Connection connection = Conection.getConexion();

    // Construir la consulta SQL para obtener los registros de ingreso
    String query = "SELECT * FROM Retiros WHERE IdUsuario IN (SELECT IdUsuario FROM CrearUsuario WHERE Nombres = ? AND Contraseña = ?)";

    // Crear el PreparedStatement y establecer los parámetros
    PreparedStatement statement = connection.prepareStatement(query);
    statement.setString(1, nombreAnterior);
    statement.setString(2, contraseñaAnterior);

    // Ejecutar la consulta y obtener los resultados
    ResultSet resultSet = statement.executeQuery();

    // Obtener el modelo de la tabla
    DefaultTableModel model = (DefaultTableModel) Tablaretiros.getModel();

    // Limpiar el contenido de la tabla
    model.setRowCount(0);

    // Recorrer los resultados y agregar las filas al modelo
    while (resultSet.next()) {
        Object[] row = new Object[4];
        row[0] = resultSet.getInt("Id");
        row[1] = resultSet.getDouble("Cantidad");
        row[2] = resultSet.getDate("Fecha_Retiro");
        row[3] = resultSet.getString("Descripcion_Retiro");
        
        model.addRow(row);
    }

    // Cerrar los recursos
    resultSet.close();
    statement.close();
    connection.close();
} catch (SQLException e) {
    e.printStackTrace();
}
  
  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNegresos;
    private javax.swing.JTable Tablaretiros;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCantidadE;
    private javax.swing.JTextField txtDescripE;
    private javax.swing.JTextField txtFechaEgreso;
    // End of variables declaration//GEN-END:variables
}
